name = "passkey-demo"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
OIDC_ISSUER = "https://accounts.google.com"
OIDC_REDIRECT_URI = "/auth/callback"

# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "SESSION_KV"
# id = "5d13904c7e414868ad8130aff8f70b6d"
kv_namespaces = [
  { binding = "SESSION_KV", id = "5d13904c7e414868ad8130aff8f70b6d" },
  { binding = "USER_KV", id = "bf0874c4197344bd9db3ffab576c66d2" },
]

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
